### ISSUE TITLE
Conditional Statements

### ISSUE THREAD

**Issue by arpitn30** [Simrankashyap/Learn-IT-Girl#1]
Given an integer, n, perform the following conditional actions:

- If n is odd, print Weird
- If  n  is even and in the inclusive range of 2 to 5, print Not Weird
- If  n is even and in the inclusive range of 6 to 20, print Weird
- If  n is even and greater than 20, print Not Weird

**Comment by Simrankashyap** [comment]
n = int(input())
if n % 2 == 1:
    print("Weird")
elif n % 2 == 0 and 2 <= n <= 5:
    print("Not Weird")
elif n % 2 == 0 and 6 <= n <= 20:
    print("Weird")
else:
    print("Not Weird")

**Comment by Simrankashyap** [comment]
close #1
