### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by arpitn30** [Simrankashyap/Learn-IT-Girl#5]
Consider a list (list = [ ]). Perform the following commands:

- _insert i e_: Insert integer e at position i.
- _print_: Print the list.
- _remove e_: Delete the first occurrence of integer e.
- _append e_: Insert integer e at the end of the list.
- _sort_: Sort the list.
- _pop_: Pop the last element from the list.
- _reverse_: Reverse the list.
Initialize your list and read in the value of n followed by n lines of commands where each command will be of the types listed above. Iterate through each command in order and perform the corresponding operation on your list.

**Comment by Simrankashyap** [comment]
list = []
n = int(input())
for i in range(n):
    a = input().split()
    if len(a) == 3:
        eval("list." + a[0] + "(" + a[1] + "," + a[2] + ")")
    elif len(a) == 2:
        eval("list." + a[0] + "(" + a[1] + ")")
    elif a[0] == "print":
        print list
    else:
        eval("list." + a[0] + "()")
