### ISSUE TITLE
Nested Lists and List Comprehensions

### ISSUE THREAD

**Issue by arpitn30** [Simrankashyap/Learn-IT-Girl#6]
You are given three integers X, Y and Z representing the dimensions of a cuboid along with an integer N. You have to print a list using list comprehension, of all possible coordinates given by (i, j, k) on a 3D grid where the sum of `i + j +k` is not equal to `N`. Here, `0 <= i <= X`, `0 <= j <= Y`, `0 <= k <= Z`. 

Sample Input
```
1
1
1
2
```

Sample Output
`[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]] `

**Comment by Simrankashyap** [comment]
X = int(input())
Y = int(input())
Z = int(input())
N = int(input())

ans = [[i, j, k] for i in range(X + 1) for j in range(Y + 1) for k in range(Z + 1) if i + j + k != N]
print(ans)
